### PR TITLE
If applied, this commit will stop some configs from panicking

### LINKED ISSUE #51: init.rx: fatal: no active view
When loading config options from ~/.config/rx/init.rx I'm getting the following errors:

```
[2020-01-04T23:46:09Z DEBUG rx::session] source: /home/pop/.config/rx/init.rx
[2020-01-04T23:46:09Z DEBUG rx::session] command: Set("checker", Bool(true))
[2020-01-04T23:46:09Z DEBUG rx::session] set `checker`: off -> on
[2020-01-04T23:46:09Z DEBUG rx::session] command: Set("grid/spacing", U32Tuple(4, 4))
[2020-01-04T23:46:09Z DEBUG rx::session] set `grid/spacing`: 8,8 -> 4,4
[2020-01-04T23:46:09Z DEBUG rx::session] command: ResizeFrame(64, 64)
thread 'main' panicked at 'fatal: no active view', src/session.rs:1293:9
```

Not every setting triggers this crash, but these do:

- [resize frame](https://github.com/cloudhead/rx/blob/master/src/session.rs#L2330)
- [slice](https://github.com/cloudhead/rx/blob/master/src/session.rs#L2490)
- [animation/delay](https://github.com/cloudhead/rx/blob/master/src/session.rs#L1153)

Seems like any command that calls `self.active_view_mut()` triggers the crash. Maybe the active view needs to be initialized before config files are loaded?

Without those config options set `rx` starts and runs well.

I'd love to contribute to the project. If I could get some direction on what changes should be made and where to make them I'd be more than happy to put together a pull request.

---

System details:

- Linux/Fedora 30 with Wayland
- rustc 1.42.0-nightly (3a3f4a7cb 2019-12-28)

Let me know if you need more system deets.

### PR DESCRIPTION
**Pull request by pop**
Some config options previously raised a panic of the following form:

	thread 'main' panicked at 'fatal: no active view', src/session.rs:1293:9
	note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

The config commands in question include:

* f/resize
* set animation/delay
* slice

Fixes #51

---

# TODO:

I'm not sure if these are worth doing, but I'm aware they're potential issues:

- [ ] Add automated tests
- [ ] Move the `session.blank(...)` call to `Session::new(...)` to simplify `fn init(...)` in `lib.rs`.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -124,8 +124,22 @@ pub fn init<P: AsRef<Path>>(paths: &[P], options: Options) -> std::io::Result<()
     let resources = ResourceManager::new();
     let base_dirs = dirs::ProjectDirs::from("io", "cloudhead", "rx")
         .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "home directory not found"))?;
-    let mut session = Session::new(win_w, win_h, hidpi_factor, resources.clone(), base_dirs)
-        .init(options.source.clone())?;
+
+    let mut session = Session::new(win_w, win_h, hidpi_factor, resources.clone(), base_dirs);
+
+    // TODO: If this is always true move this to Session::new
+    if session.views.is_empty() {
```
Comment (cloudhead) [inline src/lib.rs]: This will always be true if you move it here, so it's not required. What might be a problem though is that the blank view remains when you start the session with a bunch of files.

Comment (cloudhead) [reply src/lib.rs]: We could use `blank` as a builder function - have it consume `self` and return `Self`, just like `init`.

Then we can do `let mut session = Session::new(....).blank(..).init(...);`!

Comment (cloudhead) [reply src/lib.rs]: I think the behavior of destroying the scratch view when loading a new view already exists too, so you might not need to add anything there: https://github.com/cloudhead/rx/blob/59ac9cce2eb1b5e0f4606f21504e81c9b521ba87/src/session.rs#L1556-L1563

Comment (pop) [reply src/lib.rs]: Great feedback. I'll get to this tonight.

Related, do you think this warrants automated tests? Once I fix everything else that'll be the last change I can think to add.

Comment (pop) [reply src/lib.rs]: Could you clarify your last point? Do I need to do anything if I adopt your `Session::new(...).blank(...).init(...)?` pattern?

Comment (pop) [reply src/lib.rs]: @cloudhead Let me know what you think of my solution.
The [use of `Session::blank(...)` in `Session::edit(...)`](https://github.com/cloudhead/rx/blob/master/src/session.rs#L1439) made it really hard to refactor directly, but I was able to add a `Session::as_blank(...)` (name flexible of course) that chained nicely and didn't break existing use of `Sessoin::blank(...)`.
I'm not super happy with the workaround, but it gets the job done and I'm not experienced enough with Rust to know how to refactor `Session::blank(...)` directly without the need for `Session::as_blank(...)`.

Comment (cloudhead) [reply src/lib.rs]: > Could you clarify your last point? Do I need to do anything if I adopt your `Session::new(...).blank(...).init(...)?` pattern?

You just have to change `Session::blank` a little bit to look more like `Session::init` - it should have a type signature like `fn blank(self) -> Self`. Then, `as_blank` won't be necessary.

Automated tests are not necessary.

File: src/session.rs [hunk 2]
```diff
@@ -885,6 +885,12 @@ impl Session {
         self.edit_view(id);
     }
 
+    pub fn as_blank(mut self, fs: FileStatus, w: u32, h: u32) -> std::io::Result<Self> {
```
Comment (cloudhead) [inline src/session.rs]: You can just return `Self`, because this function cannot fail. Then you can remove the `?` in the invocation.

**Comment by cloudhead** [comment]
> Would have modified `blank(...)` but it's use in `Session::edit(...)` put that above my ...

Ahhh, I forgot about this. Your approach makes more sense then. Just follow the recommendation about `as_blank`, and rename it to `with_blank`, as that makes a little more sense I think.

**Comment by cloudhead** [comment]
Thanks!
